# Generated by Django 5.1.5 on 2026-03-12 17:06

from django.db import migrations


def create_sample_products(apps, schema_editor):
    Product = apps.get_model('orders', 'Product')
    if Product.objects.exists():
        return

    sample_items = [
        {"name": "Bananas", "price": "1.29", "description": "Fresh yellow bananas (per lb)."},
        {"name": "Milk", "price": "2.99", "description": "1 gallon of whole milk."},
        {"name": "Bread", "price": "2.49", "description": "Whole grain sandwich bread."},
        {"name": "Eggs", "price": "3.99", "description": "Dozen large eggs."},
        {"name": "Apples", "price": "1.99", "description": "Crisp apples (per lb)."},
    ]

    for item in sample_items:
        Product.objects.create(**item)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_product'),
    ]

    operations = [
        migrations.RunPython(create_sample_products),
    ]
