# Generated by Django 5.1.5 on 2026-03-12 17:14

from django.db import migrations


def seed_products(apps, schema_editor):
    Product = apps.get_model("orders", "Product")

    # Only seed if the table is empty (prevents duplicate runs)
    if Product.objects.exists():
        return

    base_items = [
        {"name": "Bananas", "price": "1.29", "description": "Fresh yellow bananas (per lb)."},
        {"name": "Milk", "price": "2.99", "description": "1 gallon of whole milk."},
        {"name": "Bread", "price": "2.49", "description": "Whole grain sandwich bread."},
        {"name": "Eggs", "price": "3.99", "description": "Dozen large eggs."},
        {"name": "Apples", "price": "1.99", "description": "Crisp apples (per lb)."},
    ]

    # Generate additional items until we reach 100 total
    adjectives = [
        "Fresh",
        "Organic",
        "Crispy",
        "Premium",
        "Deluxe",
        "Classic",
        "Savory",
        "Sweet",
        "Spicy",
        "Zesty",
    ]
    products = []

    # Add base items first
    products.extend(base_items)

    # Create additional items to reach 100 total
    item_count = 100
    idx = 1
    while len(products) < item_count:
        adjective = adjectives[(len(products) - len(base_items)) % len(adjectives)]
        name = f"{adjective} Item {idx}"
        price = f"{(idx % 15 + 1) + 0.49:.2f}"
        description = f"{adjective} grocery item number {idx}."
        products.append({"name": name, "price": price, "description": description})
        idx += 1

    # Use a generic placeholder image service for demo pictures
    for item in products:
        label = item["name"].replace(" ", "+")
        item["image_url"] = f"https://via.placeholder.com/300x200.png?text={label}"

    Product.objects.bulk_create([Product(**item) for item in products])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_add_product_image"),
    ]

    operations = [
        migrations.RunPython(seed_products),
    ]
