# Generated by Django 5.1.5 on 2026-03-12 17:16

from django.db import migrations


def refresh_product_images(apps, schema_editor):
    Product = apps.get_model("orders", "Product")

    for product in Product.objects.all():
        # Use a consistently seeded random image service for better visuals
        slug = product.name.lower().replace(" ", "-")
        product.image_url = f"https://picsum.photos/seed/{slug}/300/200"
        product.save(update_fields=["image_url"])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_seed_more_products"),
    ]

    operations = [
        migrations.RunPython(refresh_product_images),
    ]
