# Generated by Django 5.1.5 on 2026-03-12 17:31

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model('orders', 'Category')
    Product = apps.get_model('orders', 'Product')

    # Only seed if no categories exist yet
    if Category.objects.exists():
        return

    categories = {
        'Fruits': ['banana', 'apple', 'orange', 'grape', 'kiwi'],
        'Dairy': ['milk', 'cheese', 'egg', 'yogurt'],
        'Bakery': ['bread', 'bagel', 'cake', 'cookie'],
        'Beverages': ['juice', 'coffee', 'tea', 'soda'],
        'Snacks': ['chips', 'nuts', 'cracker', 'popcorn'],
        'Pantry': ['rice', 'pasta', 'cereal', 'sauce'],
        'Household': ['soap', 'shampoo', 'detergent', 'paper'],
    }

    created = {}
    for name in categories.keys():
        created[name] = Category.objects.create(name=name)

    # Assign categories based on name keywords
    for product in Product.objects.all():
        lower = product.name.lower()
        assigned = None
        for cat, keywords in categories.items():
            if any(k in lower for k in keywords):
                assigned = created[cat]
                break

        if not assigned:
            # fallback based on random distribution
            assigned = created['Pantry']

        product.category = assigned
        product.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_categories'),
    ]

    operations = [
        migrations.RunPython(seed_categories),
    ]
