# Generated by Django 5.1.5 on 2026-03-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
    ]
