# Generated by Django 5.1.5 on 2026-03-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
